<?php

namespace App\Filament\Resources;

use App\Filament\Resources\ReviewResource\Pages;
use App\Models\Review;
use App\Jobs\AnalyzeReviewAi;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Columns\TagsColumn;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Actions\Action;
use Filament\Notifications\Notification;
use Illuminate\Database\Eloquent\Builder;

class ReviewResource extends Resource
{
    protected static ?string $model = Review::class;

    protected static ?string $navigationIcon = 'heroicon-o-chat-bubble-left-right';
    
    protected static ?string $navigationGroup = 'Shop Management';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make('Review Details')
                    ->schema([
                        Forms\Components\Select::make('product_id')
                            ->relationship('product', 'name')
                            ->disabled(),
                        Forms\Components\Select::make('user_id')
                            ->relationship('user', 'name')
                            ->disabled(),
                        Forms\Components\TextInput::make('rating')
                            ->numeric()
                            ->disabled(),
                        Forms\Components\Textarea::make('comment')
                            ->columnSpanFull()
                            ->disabled(),
                    ])->columns(3),

                Forms\Components\Section::make('AI Analysis Insights')
                    ->description('These fields are automatically generated by Gemini')
                    ->schema([
                        Forms\Components\TextInput::make('sentiment')
                        ->readonly(),
                        Forms\Components\Textarea::make('ai_summary')
                        ->readonly(),
                        
                        Forms\Components\TagsInput::make('key_features')
                        ->disabled(),
                    ])->columns(1),
            ]);
    }

    public static function getEloquentQuery(): Builder
    {
        $query = parent::getEloquentQuery();
    
        if (!auth()->check()) {
            return $query;
        }
    
        $user = auth()->user();
    
        if ($user->role === 'super_admin') {
            return $query;
        }
    
        return $query->where('tenant_id', $user->tenant_id);
    }
    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('product.name')
                    ->label('Product')
                    ->sortable(),

                TextColumn::make('user.name')
                    ->label('Customer')
                    ->searchable()
                    ->sortable(),

                TextColumn::make('rating')
                    ->badge()
                    ->color('warning')
                    ->sortable(),

                // AI Sentiment Column
                TextColumn::make('sentiment')
                    ->badge()
                    ->color(function (string $state) {
                        if ($state === 'positive') return 'success';
                        if ($state === 'negative') return 'danger';
                        if ($state === 'neutral')  return 'gray';
                        return 'warning';
                    }),

                TextColumn::make('ai_summary')
                    ->label('AI Summary')
                    ->limit(40)
                    ->tooltip(fn ($record) => $record->ai_summary),

                TagsColumn::make('key_features')
                    ->label('AI Tags'),
            ])
            ->filters([
                SelectFilter::make('sentiment')
                    ->options([
                        'positive' => 'Positive',
                        'negative' => 'Negative',
                        'neutral' => 'Neutral',
                    ]),
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                
                // NEW: Manual AI Re-analyze Action
                Action::make('reAnalyze')
                    ->label('AI Re-run')
                    ->icon('heroicon-o-arrow-path')
                    ->color('info')
                    ->action(function (Review $record) {
                        AnalyzeReviewAi::dispatch($record);
                        Notification::make()
                            ->title('AI Analysis Started')
                            ->info()
                            ->send();
                    }),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListReviews::route('/'),
            'create' => Pages\CreateReview::route('/create'),
            'edit' => Pages\EditReview::route('/{record}/edit'),
        ];
    }
}